import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{}}>
        <div
          style={{
            display: "grid",
            gap: "1rem",
            placeItems: "center",
            textAlign: "center",
            height: "100vh",
            justifyContent: "center",
            alignContent: "center",
          }}
        >
          <h1>Web3 Connectors</h1>
          <div>
            <h2>eip1193</h2>
            <button>Connect</button>
          </div>
          <div>
            <h2>MetaMask</h2>
            <button>Connect</button>
          </div>
          <div>
            <h2>walletconnect-v2</h2>
            <button>Connect</button>
          </div>
        </div>
      </main>
    </>
  );
}
