import Head from "next/head";
import { Inter } from "next/font/google";
import { useWeb3React } from "@web3-react/core";
import MetaMaskCard from "@/components/MetaMaskCard";
import WalletConnectCard from "@/components/WalletConnectCard";
// useWeb3React
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { connector, account } = useWeb3React();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{}}>
        <div
          style={{
            display: "grid",
            gap: "1rem",
            placeItems: "center",
            textAlign: "center",
            height: "100vh",
            justifyContent: "center",
            alignContent: "center",
          }}
        >
          <h1>Web3 Connectors</h1>
          <div>
            <h2>Account</h2>
            <p>{account}</p>
          </div>
          <div>
            <MetaMaskCard />
          </div>
          <div>
            <WalletConnectCard />
          </div>
        </div>
      </main>
    </>
  );
}
