import Head from "next/head";
import { Inter } from "next/font/google";
import { useWeb3React } from "@web3-react/core";
import MetaMaskCard from "@/components/MetaMaskCard";
import WalletConnectCard from "@/components/WalletConnectCard";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { account, isActive, provider } = useWeb3React();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{}}>
        <div
          style={{
            display: "grid",
            gap: "1rem",
            placeItems: "center",
            textAlign: "center",
            height: "100vh",
            justifyContent: "center",
            alignContent: "center",
          }}
        >
          <h1>Web3 Connectors</h1>
          <div>
            <h2>Account</h2>
            <p>{account}</p>
          </div>
          <div>
            <MetaMaskCard />
          </div>
          <div>
            <WalletConnectCard />
          </div>
          {isActive && (
            <div>
              <h2>署名</h2>
              <button
                onClick={async () => {
                  if (provider) {
                    const message = await provider
                      .getSigner()
                      .signMessage("hello");
                    console.log(message);
                  }
                }}
              >
                hello
              </button>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
